import ProviderRedux from "@/redux/ProviderRedux";

import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ProviderRedux>{children}</ProviderRedux>
        {/* <ProviderRedux></ProviderRedux> */}
        {/* {children} */}
      </body>
    </html>
  );
}
